export const SVG_ICON = {
    BOOKMARK: '/svg/bookmark.svg',
    BULB: '/svg/bulb.svg',
    CIRCLE: '/svg/circle.svg',
    COPY: '/svg/copy.svg',
    CROWN: '/svg/crown.svg',
    DASHBOARD: '/svg/dashboard.svg',
    DOC: '/svg/doc.svg',
    DOT_0: '/svg/dot-0.svg',
    DOT_1: '/svg/dot-1.svg',
    DRAWER: '/svg/drawer.svg',
    EYE_CLOSE: '/svg/eye_close.svg',
    EYE_OPEN: '/svg/eye_open.svg',
    FOLDER: '/svg/folder-closed.svg',
    INFO: '/svg/info.svg',
    LOGIN: '/svg/login.svg',
    LOGOUT: '/svg/logout.svg',
    NIGHT: '/svg/night.svg',
    PLAY: '/svg/play.svg',
    PUZZLE: '/svg/puzzle.svg',
    SUNNY: '/svg/sunny.svg',
    SQUARE: '/svg/square.svg',
    TAP: '/svg/tap.svg',
    TICK: '/svg/tick.svg',
    TARGET: '/svg/target.svg',
    UNBOOKMARK: '/svg/unbookmark.svg',
    USER: '/svg/user.svg',
} as const;