export const SVG_ICON = {
    BOOKMARK: '/svg/bookmark.svg',
    BULB: '/svg/bulb.svg',
    COPY: '/svg/copy.svg',
    CROWN: '/svg/crown.svg',
    DASHBOARD: '/svg/dashboard.svg',
    DOC: '/svg/doc.svg',
    DRAWER: '/svg/drawer.svg',
    FOLDER: '/svg/folder-closed.svg',
    INFO: '/svg/info.svg',
    LOGIN: '/svg/login.svg',
    LOGOUT: '/svg/logout.svg',
    PLAY: '/svg/play.svg',
    PUZZLE: '/svg/puzzle.svg',
    TAP: '/svg/tap.svg',
    TARGET: '/svg/target.svg',
    UNBOOKMARK: '/svg/unbookmark.svg',
    USER: '/svg/user.svg',
} as const;