import { SVG_ICON } from "../svg-icon.constants";

export const ACTIVITY_ITEMS = {
    START_ACTIVITY: 'Start Activity',
    QUIZ: 'Quiz',
    TYPE_WORD: 'Type Word',
    FILL_BLANK: 'Fill Blank'
}

export const CARDS_ITEMS = {
    VIEW_CARDS: 'View Cards',
    DECK: 'Deck',
    MARKED: 'Marked',
    LIST: 'List'
}

export const AUTH_ITEMS = {
    REGISTER: 'Register',
    RESET_PASSWORD_REQUEST: 'Reset Password',
    RESET_PASSWORD: 'Create New Password',
    LOGIN: 'Login',
    LOGOUT: 'Logout'
};

export const EMAIL_ITEMS = {
    CONFIRM_EMAIL: 'Email Confirmation'
};

export const USER_ITEMS = {
    PROFILE: 'Profile',
    SETTINGS: 'Settings',
    PROFILE_EDIT: 'Edit',
    PROFILE_DELETE: 'Delete Profile',
    CHANGE_NAME: 'Change Username',
    CHANGE_PASSWORD: 'Change Password',
    CHANGE_LEVEL: 'Change Level',
    PROGRESS: 'My Progress',
    HELP: 'Help'
};

export const LEVEL_ITEMS = {
    A1: 'A1',
    A2: 'A2',
    B1: 'B1',
    B2: 'B2',
    C1: 'C1',
    C2: 'C2',
}

export const PROGRESS_ITEMS = {
    ALL_CARDS: 'All Cards',
    TOTAL: 'Total',
    BY_LEVEL: 'By Level',
    BY_ACTIVITY: 'By Activity'
}

export const FILTER_ITEMS = {
    BOOKMARK: 'Mark',
    THEME: 'Theme'
}

export const ICONS: Record<string, string> = {    
    [ACTIVITY_ITEMS.START_ACTIVITY]: SVG_ICON.PLAY,
    [ACTIVITY_ITEMS.QUIZ]: SVG_ICON.BULB,
    [ACTIVITY_ITEMS.TYPE_WORD]: SVG_ICON.TAP,
    [ACTIVITY_ITEMS.FILL_BLANK]: SVG_ICON.PUZZLE,

    [CARDS_ITEMS.VIEW_CARDS]: SVG_ICON.DRAWER,
    [CARDS_ITEMS.DECK]: SVG_ICON.COPY,
    [CARDS_ITEMS.MARKED]: SVG_ICON.BOOKMARK,
    [CARDS_ITEMS.LIST]: SVG_ICON.DOC,

    [AUTH_ITEMS.REGISTER]: SVG_ICON.USER,
    [AUTH_ITEMS.RESET_PASSWORD_REQUEST]: SVG_ICON.SHIELD,
    [AUTH_ITEMS.RESET_PASSWORD]: SVG_ICON.SAFE,
    [AUTH_ITEMS.LOGIN]: SVG_ICON.LOGIN,
    [AUTH_ITEMS.LOGOUT]: SVG_ICON.LOGOUT,

    [EMAIL_ITEMS.CONFIRM_EMAIL]: SVG_ICON.MAIL,

    [USER_ITEMS.PROFILE]: SVG_ICON.USER,
    [USER_ITEMS.SETTINGS]: SVG_ICON.SETTINGS,
    [USER_ITEMS.PROFILE_EDIT]: SVG_ICON.NOTE,
    [USER_ITEMS.PROFILE_DELETE]: SVG_ICON.CROSS,
    [USER_ITEMS.CHANGE_NAME]: SVG_ICON.NOTE,
    [USER_ITEMS.CHANGE_PASSWORD]: SVG_ICON.SAFE,
    [USER_ITEMS.CHANGE_LEVEL]: SVG_ICON.CROWN,
    [USER_ITEMS.PROGRESS]: SVG_ICON.DASHBOARD,
    [USER_ITEMS.HELP]: SVG_ICON.INFO,

    [LEVEL_ITEMS.A1]: SVG_ICON.DOT_0,
    [LEVEL_ITEMS.A2]: SVG_ICON.DOT_0,
    [LEVEL_ITEMS.B1]: SVG_ICON.DOT_0,
    [LEVEL_ITEMS.B2]: SVG_ICON.DOT_0,
    [LEVEL_ITEMS.C1]: SVG_ICON.DOT_0,
    [LEVEL_ITEMS.C2]: SVG_ICON.DOT_0,

    [PROGRESS_ITEMS.ALL_CARDS]: SVG_ICON.DRAWER,
    [PROGRESS_ITEMS.TOTAL]: SVG_ICON.COPY,
    [PROGRESS_ITEMS.BY_LEVEL]: SVG_ICON.CROWN,
    [PROGRESS_ITEMS.BY_ACTIVITY]: SVG_ICON.PLAY,

    [FILTER_ITEMS.BOOKMARK]: SVG_ICON.BOOKMARK,
    [FILTER_ITEMS.THEME]: SVG_ICON.FOLDER
};